#!/bin/sh
xrandr --output eDP-1-1 --mode 1920x1080 --pos 2087x1875 --rotate normal \
    --output DP-0 --mode 3440x1440 --pos 1440x435 --rotate normal --refresh 143.92 \
    --output DP-4 --mode 2560x1440 --pos 0x0 --rotate right
